### ISSUE TITLE
Running the bot as a background process?

### ISSUE THREAD

**Issue by secondubly** [zephyrtronium/robot#20]
I did a bit of research on my own and couldn't find an answer that seemed to make sense to my brain - is there a way a person could run the bot as a background process at all? I have it set up on a VPS and I would like to simply turn it on and let it run, is this at all possible via a flag or something similar?

**Comment by zephyrtronium** [comment]
I leave the bot running on a Raspberry Pi using a command along the lines of `screen -S robot robot -source=... -token=... -dash=...`. Running it with `screen` lets you detach from the session by pressing ctrl+A ctrl+D, leaving it running in the background. The `-S robot` part lets you enter `screen -r robot` while it's running to reconnect to Robot's terminal.

Other than screen, a popular option for this kind of thing is tmux, but I've never used it. If you're running it on Windows or Mac, I don't know what options exist.

**Comment by secondubly** [comment]
Ah, I forgot about screen - I did a bunch of searching to see if Go had a process manager of some sort and completely glossed over native tools 😂 screen should do nicely, thanks for the help!
