### ISSUE TITLE
logging & metrics

### ISSUE THREAD

**Issue by zephyrtronium** [zephyrtronium/robot#29]

**Comment by zephyrtronium** [comment]
Set up otel slog handler. Ideally use message IDs as trace IDs where possible, but not strictly necessary. Add more logging especially in [tmiMessage](https://github.com/zephyrtronium/robot/blob/master/privmsg.go#L25) and its descendants. @FreezingSnail @FreezingSnail

**Comment by FreezingSnail** [comment]
@smantic 🪨 ⭐ 👨‍💻
