### ISSUE TITLE
robot-init not recognized

### ISSUE THREAD

**Issue by bitbot-marina** [zephyrtronium/robot#33]
I'm getting the following error when I try to initialize the database for my bot:
![image](https://user-images.githubusercontent.com/15271348/227323984-d582bbef-1db6-4881-a62f-f77765624944.png)

robot -help works, so I'm wondering what I might be doing wrong here?

**Comment by zephyrtronium** [comment]
Try running just `go install github.com/zephyrtronium/robot/cmd/robot-init@latest`, then run `robot-init` again. If that still doesn't work, try closing your PowerShell and opening a new one and then try once more from the top. If *that* doesn't work, we'll have to figure out what's going on.
