### ISSUE TITLE
SQLite Error: 'no such table: knowledge' when running the bot

### ISSUE THREAD

**Issue by KingsRequin** [zephyrtronium/robot#89]
Hi, I'm getting this error while trying to run the bot:

```
time=2024-11-18T13:31:36.397+01:00 level=ERROR msg="couldn't speak" trace=9415b845-94bf-4280-8709-442aeaf8f406 in=#azrael_ttv command=speak args=map[prompt:] err="couldn't speak: couldn't prepare term selection: sqlite: prepare \"SELECT id, suffix FROM knowledge WHERE tag = :tag AND prefix >= :lower AND prefix < :upper AND LIKELY(deleted IS NULL)\": SQL logic error: no such table: knowledge"
```

Could you help me fix this issue?

**Comment by zephyrtronium** [comment]
I was getting this error while trying to speak with the CLI with the bot still running. I think it might be related to the connection pool manager. Just to double-check, could you share the `[db]` section of your config?

**Comment by KingsRequin** [comment]
Here it is, I haven't changed anything
```[db]
# sqlbrain is an SQLite3 connection string for the brain database.
# If sqlbrain is defined, the SQLite3 implementation is used.
sqlbrain = 'file:$ROBOT_SQLITE'
# kvbrain is the directory in which learned knowledge is stored.
# If kvbrain is defined, the Badger implementation is used.
#kvbrain = '$ROBOT_KNOWLEDGE'
# kvflag configures the brain database as a Badger "superflag" string.
# It is ignored when not using the Badger implementation.
#kvflag = ''
# privacy is an SQLite3 connection string for the database where privacy
# information is stored.
privacy = 'file:$ROBOT_SQLITE'
# spoken is an SQLite3 connection string for the database where generated
# message traces are stored.
spoken = 'file:$ROBOT_SQLITE'

# global includes chat settings that apply to all channels.
[global]
# block is a regex that blocks messages from being learned in any channel.
# Unlike most string options, it is not expanded with environment variables.
block = '(?i)bad\s+stuff[^$x]'
```

**Comment by zephyrtronium** [comment]
The `$ROBOT_SQLITE` parts there are environment variable references. It seems like not having that defined is what causes this error. (It just occurred to me that that also explains why I was having problems myself.) I'll look into improving the error message for this scenario.

In the mean time, the easiest thing for you to do will be to replace `$ROBOT_SQLITE` with something like `robot.sqlite` everywhere in that section.

**Comment by KingsRequin** [comment]
it works!
I would have another question too, is the bot able to learn in languages other than English?
and is it possible to modify the prompt to manage its behavior/mood?

**Comment by zephyrtronium** [comment]
Robot can learn languages other than English as long as they use spaces to separate words. Command invocations and outputs are English only, though.

Robot doesn't have a concept of behavior or mood beyond the fixed emotes that are added randomly to messages. The algorithm just picks words at random.
